#!/bin/bash
if [[ $1 == '-r' ]] 
then 
  `setxkbmap -option -option grp:alt_shift_toggle -option terminate:ctrl_alt_bksp`
else
  `setxkbmap -option grp:alt_shift_toggle -option terminate:ctrl_alt_bksp -option caps:ctrl_modifier`
fi
